import Header from "@/components/Header";
import Head from "next/head";
import { NextPageWithProperties } from "./_app";
import useSession from "@/utils/useSession";

const Protected: NextPageWithProperties = () => {
  const session = useSession();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        <h1>This is a protected page</h1>
        <div>Your username: {session.user!.username}</div>
        <div>Your email: {session.user!.email}</div>
      </main>
    </>
  );
};

Protected.isPublic = false;

export default Protected;
